#!/usr/bin/env bash

# INSTALLED BY ANSIBLE
# SOURCE IN `Ruby/chruby/files/chruby-run`

VSN_FILE=~/.ruby-version

function abort_no_input() {
  echo "chruby-run <cmd>"
  echo "runs the <cmd> using the global ruby defined in $VSN_FILE"
  exit 1
}

function abort_no_global() {
  echo "Error: no global ruby (defined in $VSN_FILE)"
  exit 1
}


function global_version() {
  cat $VSN_FILE
}

[[ "$#" == "0" ]]  && abort_no_input
[ -f $VSN_FILE ] || abort_no_global

chruby-exec `global_version` -- "$@"
