#!/bin/env bash 

PATH=/sbin:/bin:/usr/sbin:/usr/bin
DAEMON_SBIN=/usr/sbin/hostapd
DAEMON_DEFS=/etc/default/hostapd
DAEMON_CONF=/etc/hostapd/hostapd.conf
NAME=hostapd
DESC="advanced IEEE 802.11 management"
PIDFILE=/var/run/hostapd.pid

[ -x "$DAEMON_SBIN" ] || exit 0
[ -s "$DAEMON_DEFS" ] && . /etc/default/hostapd
[ -n "$DAEMON_CONF" ] || exit 0

DAEMON_OPTS="-B -P $PIDFILE $DAEMON_OPTS $DAEMON_CONF"

. /lib/lsb/init-functions

# Choose the hostapd binary to use depending on what card is plugged in.
switch_bin()
{
	found=0
	if [ ! -f /usr/sbin/hostapd.new ]; then
		echo "ERROR - /usr/sbin/hostapd.new does not exist! Exiting";
		exit 1;
	fi
	if [ ! -f /usr/sbin/hostapd.stock ]; then
		echo "ERROR - /usr/sbin/hostapd.stock does not exist! Exiting";
		exit 1;
	fi
	AR9271=0
	lsusb | grep AR9271;
	if [ $? -eq 0 ]; then
		AR9271=1
	fi
	lsusb | grep RT3...;
	if [ $? -eq 0 ] || [ $AR9271 -eq 1 ]; then
		echo "Found Ralink wifi card."
		found=1;
		rm -f /usr/sbin/hostapd; 
		ln -s /usr/sbin/hostapd.stock /usr/sbin/hostapd; 
	fi

	lsusb | grep IMC\ Networks; 
	if [ $? -eq 0 ]; then 
		echo "Found Atheros wifi card."
		found=1;
		rm -f /usr/sbin/hostapd; 
		ln -s /usr/sbin/hostapd.stock /usr/sbin/hostapd; 
	fi

	if [ $found -eq 0 ]; then
		echo "Using new hostapd"
		rm -f /usr/sbin/hostapd; 
		ln -s /usr/sbin/hostapd.new /usr/sbin/hostapd; 
	fi	
}

switch_bin
log_daemon_msg "Starting $DESC" "$NAME"
start-stop-daemon --start --oknodo --quiet --exec "$DAEMON_SBIN" \
  --pidfile "$PIDFILE" -- $DAEMON_OPTS >/dev/null
log_end_msg "$?"

