# Copied by Ansible - Start
[ -f ~/.bashrc_base ]                && source ~/.bashrc_base
[ -f ~/.asdf/asdf.sh ]               && source ~/.asdf/asdf.sh
[ -f ~/.asdf/completions/asdf.bash ] && source ~/.asdf/completions/asdf.bash
# Copied by Ansible - End
