# incus-compose 
# https://github.com/bketelsen/incus-compose
# https://github.com/bketelsen/incus-compose/releases 

- name: create pkg directory
  file: 
    path:  /home/{{gen_user}}/.pkg/incus/{{incom_vsn}}
    state: directory 
    group: "{{gen_user}}" 
    owner: "{{gen_user}}"

- name: get executable
  get_url:
    url:  http://cblob-host:5000/incus/{{incom_vsn}}_incus-compose 
    dest: /home/{{gen_user}}/.pkg/incus/{{incom_vsn}}_incus-compose
    group: "{{gen_user}}" 
    owner: "{{gen_user}}"

- name: install symlink
  become: true
  file: 
    src:   /home/{{gen_user}}/.pkg/incus/{{incom_vsn}}_incus-compose
    dest:  /usr/local/bin/incus-compose
    state: link
    force: yes
    mode: 'a+rx'

