---

- name: Update apt-cache
  apt:
    update_cache: yes
    autoclean: yes
    autoremove: yes

- name: install tools
  become: true
  apt: pkg={{ item }} state=latest install_recommends=yes
  with_items:
    - gpg
    - pass
    - suckless-tools
