---

# freecad
# https://github.com/FreeCAD/FreeCAD/releases
# https://github.com/dprojects/Woodworking/releases

- include_tasks: install.yml
  # NOTE: We want "has_gui" and "is_physical"
  when: has_gui | bool
