#!/bin/bash
# use this script to rebuilt jq on Raspbian/RPI
 
sudo apt-get install make libtool bison flex 

wget "https://github.com/stedolan/jq/releases/download/jq-1.5/jq-1.5.tar.gz"

tar xf jq-1.5.tar.gz

cd jq-1.5

./configure --disable-maintainer-mode   &&
make LDFLAGS=-all-static   
 
