---

# beancount

# see `install_beancount`

# - name: add PPA
#   apt_repository: repo=ppa:mbudde/beancount 
#
# - name: add beancount 
#   apt: pkg={{item}} state=latest force=yes
#   with_items:
#     - beancount
#     - hbeancount 
#     - hbeancount-ui
#     - hbeancount-web

